pipeline:
  syntaxcheck:
    image: monachus/hugo
    commands:
        - cd site; ./build/build.sh syntax

  deploy:
    image: tmaier/docker-compose
    commands:
      # Install git
      - apk add -q git

      # Clone the git remository
      # Make the signatures file available to the PMPC website
      # Build the docker container
      # Clean things up
      - git clone https://git.fsfe.org/pmpc/website.git /tmp/pmpc-build && cd /tmp/pmpc-build/ && cp /tmp/signatures/signatures.json site/data/signatures/signatures.json && docker build -t pmpc .

      # Run docker compose
      - docker-compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/forms/pmpc:/tmp/signatures:ro
    when:
       event: [push, tag, deployment]
       branch: master

