# == SHQIP ==

# General strings
[Languages.sq]
  languageCode  = "sq"
  languageName  = "Shqip"
  description   = "Paratë Publike, Kodi Publik - Një fushatë "
  fsdefinition  = "Softwari i lirë i jep gjithësecilit të drejtën ta përdori, studiojë, ta shpërndajë dhe ta përmirësoj. Kjo e drejtë ndihmon mbështetjen e lirive të tjera bazike si: liria e shprehjes, shtypit dhe privatësisë."


# Navigation
[Languages.sq.navigation]
[Languages.sq.navigation.links]
  start     = "Nisje"
  about     = "Rreth"
  arguments = "Arsye"
  action    = "Vepro"
  spread    = "Përhap lajmin"


# Start banner
[Languages.sq.start]
  subtitle1   = "Përse softuerët e financuar nga taksat e qytetarëve nuk janë sjellë si Softuerë të Lirë?"
  subtitle2   = "Ne duam që legjislacioni që kërkon që softueri i financuar publikisht i zhvilluar për sektorin publik të vihet në dispozicion të publikut në kuadrin e një programi [Softuer i Lirë dhe i Hapur] (https://fsfe.org/freesoftware/basics/summary.html 'Software i Lirë i jep të gjithëve të drejtën për përdorim, studim, ndarje dhe përmirësim të softuerit. Kjo e drejtë ndihmon në mbështetje të lirive të tjera themelore si liria e fjalës, shtypit dhe privatësisë. '). Nëse është para publike, duhet të jetë edhe kod publik."
  subtitle3   = "**Kodi i paguar nga njerëzit duhet të jetë i disponueshëm për njerëzit!**" 


# About section
[Languages.sq.about]
  headline    = "Duket e vështirë? Nuk është. Është shumë e thjeshtë!"
  buttonText  = "Më shumë përparësi"

# Arguments section
[Languages.sq.arguments]
  headline    = "Arsyet për Kod Publik"
  followup    = "A besoni se Software-i i Lirë duhet të jetë opsioni i parazgjedhur për softuerin e financuar publikisht? **Le t'i bindim përfaqësuesit tuaj politikë!**"
  buttonText  = "Nënshkruaj Letrën e Hapur"
[[Languages.sq.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Kursimet e taksave"
  description = "Aplikacione të ngjashme nuk duhet të programohen nga zeroja çdo herë."
[[Languages.sq.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Bashkëpunimi"
  description = "Projektet e mëdha mund të ndajnë ekspertizën dhe kostot."  
[[Languages.sq.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Në shërbim të publikut"
  description = "Aplikacionet e paguara nga publiku duhet të jenë të disponueshme për të gjithë."
[[Languages.sq.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Nxitja e inovacionit"
  description = "Me procese transparente, të tjerët nuk duhet të rishpikin rrotën."


# Action section
[Languages.sq.action]
  headline      = "Thuaji përfaqësuesve tuaj!"
  intro         = "Në  [**letrën e hapur**](openletter/) ne kërkojmë:" 
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Zbatimi i legjislacionit që kërkon që softueri i financuar publikisht i zhvilluar për sektorin publik të vihet në dispozicion të publikut në kuadrin e një programi [Free and Open Source Software] (https://fsfe.org/freesoftware/basics/summary.html 'Software-i i Lirë i jep të gjithëve të drejtën për të përdorur ,studiuar, shpërndarjen dhe përmirësimi i softuerit. Kjo e drejtë ndihmon në mbështetjen e lirive të tjera themelore si liria e fjalës, shtypit dhe privatësisë. ')”"
 description   = "**$ORGS** organizata dhe **$INDS** Njerëzit tashmë e mbështesin këtë thirrje për veprim duke nënshkruar letrën tonë të hapur (openletter /). Ju gjithashtu mund të na ndihmoni të kemi një ndikim shumë më të madh duke e nënshkruar atë! Ne do t'i dorëzojmë të gjitha nënshkrimet përfaqësuesve në mbarë Evropën që debatojnë për lirinë e softuerit në administratën publike."


[Languages.sq.action.box]
  text      = "Tashmë **$INDS SIGNATURES** – firmosni letrën e hapur tani!"

[Languages.sq.action.form]
  name      = "Emri (e nevojshme)"
  email     = "Email (i nevojshëm)"
  country   = "Shteti juaj"
  zip       = "Kodi Postar"
  comment   = "Komenti juaj (maks. 140 karaktere)"
  permPriv  = "Kam lexuar dhe pranoj [deklaratën e privatësisë](privacy/)"
  permNews  = "Dua të mbetem i informuar për të ardhmen e kësaj fushate"
  permPub   = "Dua që firma ime të shfaqet në [listën e firmave](openletter/all-signatures)"
  submit    = "Firmos tani!"


# Organisations section
[Languages.sq.organisations]
  headline          = "Organizatat Mbështetëse"
  text              = "Organizatat e mëposhtme mbështesin [letrën tonë të hapur] (openletter /). Nëse organizata juaj është gjithashtu e interesuar të bashkohet me thirrjen për Kodin Publik, ju lutemi [na kontaktoni] (mailto: contact@fsfe.org)."


# Spread the word section
[Languages.sq.spread]
  headline          = "Përhap fjalën!"
  promoText         = "Porosisni afishet dhe fletushkat më të fundit nga FSFE"
  promoButtonText   = "Merrni material promovues"
  shareText         = "Tregoju miqve dhe ndjekësve tuaj rreth Kodit Publik:"
  defaultSocialText = "Nëse është para publike, duhet të jetë edhe kod publik. Unë e mbështes këtë thirrje për më shumë kod publik nën një licencë të Softuerit të Lirë:"


# Legal Section
[Languages.sq.legal]
  by            = "Kjo është një fushatë nga  Free Software Foundation Europe"
  imprint       = "Stampa"
  privacy       = "Privatësia"
  transparency  = "Trasparenca"
  contribute1   = "Kodi i këtij website është në Free Software"
  contribute2   = "Jeni të mirëpritur të kontribuoni!"
  license       = "Kjo punë është nën licensën e [Creative Commons BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.sq.language]
  description = "Lexoni këtë faqe në një gjuhë tjetër"


# 404 Error Page
[Languages.sq.error]
  headline    = "Gabim 404 - Faqja nuk u gjend"
  description = "Faqja që kërkoni nuk ekziston."
  button      = "Kthehu te faqja e fillimit"


# Specific sub-pages
[Languages.sq.subpage]
[Languages.sq.subpage.signatures]
  headline      = "Firmat Individuale të Letrës së Hapur"
  description   = "Më poshtë janë nënshkrimet e nënshkruesve të cilët ranë dakord që emrat e tyre të bëhen publike. Bëhu i ardhshmi!"
  allSignatures = "Shihni [të gjitha nënshkrimet publike](all-signatures/)."
  tableName     = "Emri"
  tableCountry  = "Shteti"
  tableComment  = "Koment"
