# == РУССКИЙ ==

# General strings
[Languages.ru]
  languageCode  = "ru"
  languageName  = "Русский"
  description   = "Бюджетные деньги, открытый код! - кампания за публикацию программного обеспечения, разработанного с государственным финансированием, в качестве свободного ПО  с открытым кодом."
  fsdefinition  = "Свободное программное обеспечение дает право каждому использовать, изучать, распространять и совершенствовать программное обеспечение. Это право способствует другим фундаментальным свободам, как свобода слова, прессы и неприкосновенность частной жизни."


# Navigation
[Languages.ru.navigation]
[Languages.ru.navigation.links]
  start     = "Главная"
  about     = "О нас"
  arguments = "Почему это важно"
  action    = "Время действовать"
  spread    = "Поделиться"


# Start banner
[Languages.ru.start]
  subtitle1   = "Почему программное обеспечение, приобретенное на бюджетные средства - не свободное ПО?"
  subtitle2   = "Мы требуем изменения законодательства, чтобы код программного обеспечения, вновь разрабатываемого или закупаемого для государственного сектора, был общедоступен в соответствии с лицензиями  [свободного программного обеспечения](https://fsfe.org/freesoftware/basics/summary.html 'Свободное программное обеспечение дает право каждому использовать, изучать, распространять и совершенствовать программное обеспечение. Это право способствует другим фундаментальным свободам, как свобода слова, прессы и неприкосновенность частной жизни'). Если это бюджетные деньги, то это должен быть открытый код!"
  subtitle3   = "**Код, за который заплатили граждане, должен быть общедоступным!**" 


# About section
[Languages.ru.about]
  headline    = "Звучит сложно? Это не так! Все очень просто!"
  buttonText  = "Больше преимуществ"


# Arguments section
[Languages.ru.arguments]
  headline    = "Доводы в пользу СПО"
  followup    = "Согласны ли Вы, что если речь идет о программном обеспечении, финансируемом из бюджета, то предпочтение по умолчанию должно быть отдано свободному программному обеспечению? **Тогда, давайте убедим в этом наших политиков!**"
  buttonText  = "Подпишите открытое письмо"
[[Languages.ru.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Экономия налогов"
  description = "Нет необходимости разрабатывать одни и те же приложения заново."
[[Languages.ru.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Сотрудничество"
  description = "Большинство расходов может быть оптимизировано, благодаря эффективному распределению ресурсов между разными проектами"  
[[Languages.ru.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Польза для общества"
  description = "Приложения, разработанные на средства налогоплательщиков, должны быть общедоступны."
[[Languages.ru.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Содействие инновациям"
  description = "Прозрачность процессов позволяет не изобретать велосипед вновь каждый раз."


# Action section
[Languages.ru.action]
  headline      = "Скажите Вашим государственным служащим"
  intro         = "В нашем [**открытом письме**](openletter/) мы требуем:" 
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Принять законодательные меры, требующие, чтобы программное обеспечение, финансируемое из бюджета и разработанное для государственного сектора, было общедоступным в соответствии с лицензиями [открытого и свободного программного обеспечения](https://fsfe.org/freesoftware/basics/summary.html 'Свободное программное обеспечение дает право каждому использовать, изучать, распространять и совершенствовать программное обеспечение. Это право способствует другим фундаментальным свободам, как свобода слова, прессы и неприкосновенность частной жизни.').”"
  description   = "**$ORGS** организаций и **$INDS** частных лиц уже поддержали эту инициативу, подписав [открытое письмо](openletter/). Вы можете помочь нам оказать больше влияния! Мы передадим открытое письмо со всеми подписями представителям властей, отвечающим за принятие решений по использованию свободного ПО в административных учреждениях по всей Европе."

[Languages.ru.action.box]
  text      = "**$INDS ПОДПИСЕЙ СОБРАНО** – подписать сейчас!"

[Languages.ru.action.form]
  name      = "Имя (обязательное поле)"
  email     = "Email (обязательное поле)"
  country   = "Страна"
  zip       = "Индекс"
  comment   = "Ваш комментарий (не более 140 знаков)"
  permPriv  = "Я прочитал и согласен с [политикой защиты персональных данных](privacy/)"
  permNews  = "Я хочу получать актуальную информацию о ходе кампании"
  permPub   = "Я хочу чтобы мое имя появилось в [списке подписавших открытое письмо](openletter/all-signatures)"
  submit    = "Подписать!"


# Organisations section
[Languages.ru.organisations]
  headline          = "Поддерживающие организации"
  text              = "Эти организации поддерживают нашу  [инициативу](openletter/). Если ваша организация тоже заинтересована в этой кампании, пожалуйста, [свяжитесь с нами](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.ru.spread]
  headline          = "Расскажите другим!"
  promoText         = "Закажите стикеры, флайеры и другие материалы FSFE"
  promoButtonText   = "Заказать информационные материалы"
  shareText         = "Расскажите своим друзьям и подписчикам о кампании:"
  defaultSocialText = "Если это бюджетные деньги, то это должен быть общедоступный код. Я поддерживаю призыв к использованию свободного программного обеспечения с открытым кодом!"


# Legal Section
[Languages.ru.legal]
  by            = "Эта кампания проводится организацией Free Software Foundation Europe"
  imprint       = "Информация"
  privacy       = "Защита персональных данных"
  transparency  = "Раскрытие информации"
  contribute1   = "Исходный код этого сайта является свободным и открытым." 
  contribute2   = "Мы рады, если вы хотите помочь нам стать лучше!"
  license       = "Мы работаем в соответствии с лицензией [Creative Commons BY-SA 4.0 Licence](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.ru.language]
  description = "Выбрать язык"


# 404 Error Page
[Languages.ru.error]
  headline    = "Ошибка 404 – Страница не найдена"
  description = "К сожалению, страница, которую вы ищете, не существует."
  button      = "Вернуться на главную страницу"


# Specific sub-pages
[Languages.ru.subpage]
[Languages.ru.subpage.signatures]
  headline      = "Список подписей"
  description   = "Ниже список тех, кто подписал письмо и согласился опубликовать свое имя. Ваше имя тоже может появиться тут!"
  allSignatures = "Показать [все подписи](all-signatures/)."
  tableName     = "Имя"
  tableCountry  = "Страна"
  tableComment  = "Комментарий"
